/**
 * Find every calibrated criterion's neutral point in the stored history.
 *
 *   pnpm run calibrate                     # writes src/analysis/calibration-table.ts
 *   pnpm run calibrate -- --weeks 26       # how far back to sample (default 26)
 *   pnpm run calibrate -- --out /tmp/t.ts  # somewhere else
 *
 * Scores every stored symbol — the watchlist and the reference universe alike —
 * at one instant per week, collects each calibrated figure as the scorer reads
 * it (`collectCalibrated`), and writes the 101 percentiles of each. Every symbol
 * contributes at most one instant per week, so a stock that has been stored for
 * longer counts for longer, but a busy week of refreshes does not count more
 * than a quiet one.
 *
 * The output is code: reviewed, committed, and a change to it re-scores the
 * history like any other scoring change. Figures come from the payloads, never
 * from returns, so calibrating does not fit the score to what happened next.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';

import { getConfig } from '../config.js';
import { computeAllMetrics } from '../analysis/computeMetrics.js';
import { collectCalibrated, CriterionDistribution, percentiles } from '../analysis/calibration.js';
import { computeFactorScore } from '../analysis/score.js';
import { StockFinancials } from '../types.js';
import { logger } from '../utils/logger.js';
import { closePool, waitForDatabase } from './client.js';
import { storedInputs } from './rescore.js';
import { listSymbols, snapshotHistory } from './store.js';

const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

/** The newest financials snapshot of each week, going back `weeks`. */
async function weeklyInstants(symbol: string, weeks: number): Promise<number[]> {
  const since = new Date(Date.now() - weeks * WEEK_MS);
  const history = await snapshotHistory<StockFinancials>(symbol, 'financials', since);
  const byWeek = new Map<number, number>();
  for (const row of history) {
    const t = row.capturedAt.getTime();
    byWeek.set(Math.floor(t / WEEK_MS), t);
  }
  return [...byWeek.values()].sort((a, b) => a - b);
}

export async function calibrate(weeks: number): Promise<{
  table: Record<string, CriterionDistribution>; symbols: number; observations: number;
}> {
  const symbols = await listSymbols('all');
  const byKey = new Map<string, { values: number[]; symbols: Set<string> }>();
  let observations = 0;
  let scoredSymbols = 0;

  for (const symbol of symbols) {
    const instants = await weeklyInstants(symbol, weeks);
    let scored = false;
    for (const at of instants) {
      const inputs = await storedInputs(symbol, at);
      if (!inputs) continue;
      collectCalibrated((key, value) => {
        const entry = byKey.get(key) ?? { values: [], symbols: new Set<string>() };
        entry.values.push(value);
        entry.symbols.add(symbol);
        byKey.set(key, entry);
      }, () => computeFactorScore({
        financials:       inputs.financials,
        metrics:          computeAllMetrics(inputs.financials, inputs.rates, inputs.sectorMedians),
        sectorMedians:    inputs.sectorMedians,
        marketSignals:    inputs.marketSignals,
        technicalSignals: inputs.technicalSignals,
      }));
      observations++;
      scored = true;
    }
    if (scored) scoredSymbols++;
  }

  const table: Record<string, CriterionDistribution> = {};
  for (const [key, { values, symbols: from }] of [...byKey.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    table[key] = { quantiles: percentiles(values).map((q) => Number(q.toPrecision(6))), n: values.length, symbols: from.size };
  }
  return { table, symbols: scoredSymbols, observations };
}

function render(result: Awaited<ReturnType<typeof calibrate>>, weeks: number): string {
  const lines = [
    '// Generated by `pnpm run calibrate` (src/db/calibrate.ts) — do not edit by hand.',
    `// ${result.symbols} symbols, ${result.observations} weekly observations over the last ${weeks} weeks.`,
    '',
    "import type { CalibrationTable } from './calibration.js';",
    '',
    'export const CALIBRATION_META = {',
    `  generatedAt: ${JSON.stringify(new Date().toISOString())} as string | null,`,
    `  symbols: ${result.symbols},`,
    `  observations: ${result.observations},`,
    '} as const;',
    '',
    'export const CALIBRATION: CalibrationTable = {',
  ];
  for (const [key, d] of Object.entries(result.table)) {
    lines.push(`  ${JSON.stringify(key)}: {`);
    lines.push(`    n: ${d.n}, symbols: ${d.symbols},`);
    lines.push(`    quantiles: [${d.quantiles.join(', ')}],`);
    lines.push('  },');
  }
  lines.push('};', '');
  return lines.join('\n');
}

const isMain = process.argv[1]?.endsWith('calibrate.ts') || process.argv[1]?.endsWith('calibrate.js');

if (isMain) {
  const args = process.argv.slice(2);
  const flag = (name: string): string | undefined => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const weeks = Number(flag('--weeks') ?? 26);
  const out = resolve(flag('--out') ?? 'src/analysis/calibration-table.ts');

  (async () => {
    getConfig();
    await waitForDatabase();
    const result = await calibrate(weeks);
    writeFileSync(out, render(result, weeks));
    logger.success(
      `Calibrated ${Object.keys(result.table).length} criteria from ${result.symbols} symbols `
      + `(${result.observations} observations) → ${out}`,
    );
    await closePool();
  })().catch(async (e) => {
    logger.error(`Calibration failed: ${(e as Error).message}`);
    await closePool();
    process.exit(1);
  });
}
