// Generated by `pnpm run backtest -- --write-weights` (src/backtest/run.ts) — do not edit by hand.
// No fit committed: the judgment weights in score.ts are in force.

import type { FittedWeights, WeightFitMeta } from './score.js';

export const FITTED_WEIGHTS_META: WeightFitMeta | null = null;

export const FITTED_WEIGHTS: FittedWeights | null = null;
